[2024-09-02T08:43:10.183+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-02T08:43:10.584+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_northwind.transform_data.staging_dim_products.run scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-09-02T08:43:10.882+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_northwind.transform_data.staging_dim_products.run scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-09-02T08:43:10.883+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 3
[2024-09-02T08:43:11.381+0000] {taskinstance.py:2879} INFO - Executing <Task(DbtRunLocalOperator): transform_data.staging_dim_products.run> on 2024-09-01 00:00:00+00:00
[2024-09-02T08:43:11.391+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_northwind', 'transform_data.staging_dim_products.run', 'scheduled__2024-09-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_northwind.py', '--cfg-path', '/tmp/tmppq2r401k']
[2024-09-02T08:43:11.392+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask transform_data.staging_dim_products.run
[2024-09-02T08:43:11.392+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-02T08:43:11.392+0000] {standard_task_runner.py:72} INFO - Started process 271 to run task
[2024-09-02T08:43:11.986+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_northwind.transform_data.staging_dim_products.run scheduled__2024-09-01T00:00:00+00:00 [running]> on host edf1a788419f
[2024-09-02T08:43:13.090+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_northwind' AIRFLOW_CTX_TASK_ID='transform_data.staging_dim_products.run' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-01T00:00:00+00:00'
[2024-09-02T08:43:13.093+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-02T08:43:44.084+0000] {local.py:186} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2024-09-02T08:43:44.085+0000] {local.py:331} INFO - Cloning project to writable temp directory /tmp/tmpc0t0keek from /opt/airflow/dbt/dbt-northwind-rds/northwind
[2024-09-02T08:43:44.086+0000] {local.py:342} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_northwind__transform_data/target/partial_parse.msgpack
[2024-09-02T08:43:44.186+0000] {config.py:320} INFO - Profile caching is enable.
[2024-09-02T08:43:44.386+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 267, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 530, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 346, in run_command
    with self.profile_config.ensure_profile() as profile_values:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 321, in ensure_profile
    cached_profile_path = self._get_profile_path(use_mock_values)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 297, in _get_profile_path
    current_profile_version = self.profile_mapping.version(self.profile_name, self.target_name, use_mock_values)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 98, in version
    profile = self.profile
              ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/postgres/user_pass.py", line 44, in profile
    **self.mapped_params,
      ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 318, in mapped_params
    mapped_params[dbt_field] = self.get_dbt_value(dbt_field)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 295, in get_dbt_value
    value = self._get_airflow_conn_field(airflow_field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 272, in _get_airflow_conn_field
    value = getattr(self.conn, airflow_field, None)
                    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 146, in conn
    conn = BaseHook.get_connection(self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_northwind_conn` isn't defined
[2024-09-02T08:43:44.488+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_northwind, task_id=transform_data.staging_dim_products.run, run_id=scheduled__2024-09-01T00:00:00+00:00, execution_date=20240901T000000, start_date=20240902T084310, end_date=20240902T084344
[2024-09-02T08:43:44.783+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-02T08:43:44.785+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task transform_data.staging_dim_products.run (The conn_id `postgres_northwind_conn` isn't defined; 271)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 267, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 530, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 346, in run_command
    with self.profile_config.ensure_profile() as profile_values:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 321, in ensure_profile
    cached_profile_path = self._get_profile_path(use_mock_values)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 297, in _get_profile_path
    current_profile_version = self.profile_mapping.version(self.profile_name, self.target_name, use_mock_values)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 98, in version
    profile = self.profile
              ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/postgres/user_pass.py", line 44, in profile
    **self.mapped_params,
      ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 318, in mapped_params
    mapped_params[dbt_field] = self.get_dbt_value(dbt_field)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 295, in get_dbt_value
    value = self._get_airflow_conn_field(airflow_field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 272, in _get_airflow_conn_field
    value = getattr(self.conn, airflow_field, None)
                    ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 146, in conn
    conn = BaseHook.get_connection(self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_northwind_conn` isn't defined
[2024-09-02T08:43:44.880+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-02T08:43:45.098+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-02T08:43:45.181+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
